-- Seed data: the 376-student roster.
--
-- CORRECTED SOURCE: names/classes come from student-directory.html in
-- artificialiman/UTMEDaily (Tendercare/Directory/student-directory.html),
-- confirmed authoritative directly. An earlier version of this file used
-- tcc_broadsheet.html instead, cross-checked against admin_broadsheet.html
-- for confidence — but both of those files turned out to share the SAME
-- column-shift bug from TCH-2025-234 onward (143 students, the whole SS1
-- Actuarial through SS3 Actuarial range), so agreeing with each other
-- wasn't actually independent verification. student-directory.html doesn't
-- have that shift and is confirmed correct by the person who runs the school.
--
-- Class/subject structure (classes, subjects, class_subjects below) still
-- comes from tcc_broadsheet.html — that part was never in question, only
-- the per-student ID-to-name mapping was affected.

insert into classes (id, label, arm, sort_order) values
('JSS1A', 'JSS1A', null, 1),
('JSS1B', 'JSS1B', null, 2),
('JSS2A', 'JSS2A', null, 3),
('JSS2B', 'JSS2B', null, 4),
('JSS3A', 'JSS3A', null, 5),
('JSS3B', 'JSS3B', null, 6),
('SS1 Science', 'SS1 Sci', 'Science', 7),
('SS1 Actuarial', 'SS1 Act', 'Actuarial', 8),
('SS2 Science', 'SS2 Sci', 'Science', 9),
('SS2 Actuarial', 'SS2 Act', 'Actuarial', 10),
('SS3 Science', 'SS3 Sci', 'Science', 11),
('SS3 Actuarial', 'SS3 Act', 'Actuarial', 12);

insert into subjects (name) values
('Accounting'),
('Agriculture'),
('BT'),
('Basic Science'),
('Biology'),
('Business Studies'),
('CCA'),
('CRS'),
('Chemistry'),
('Cit & Heritage'),
('Commerce'),
('Computer'),
('DT'),
('Data Processing'),
('Economics'),
('English'),
('French'),
('Further Math'),
('Government'),
('History'),
('Horticulture'),
('IRS'),
('Literature'),
('Livestock'),
('Marketing'),
('Mathematics'),
('NVE'),
('PHE'),
('Physics'),
('Social & Cit Ed'),
('Yoruba')
on conflict (name) do nothing;

insert into class_subjects (class_id, subject_id) values
('JSS1A', (select id from subjects where name = 'English')),
('JSS1A', (select id from subjects where name = 'Mathematics')),
('JSS1A', (select id from subjects where name = 'Basic Science')),
('JSS1A', (select id from subjects where name = 'CCA')),
('JSS1A', (select id from subjects where name = 'CRS')),
('JSS1A', (select id from subjects where name = 'History')),
('JSS1A', (select id from subjects where name = 'Horticulture')),
('JSS1A', (select id from subjects where name = 'Business Studies')),
('JSS1A', (select id from subjects where name = 'DT')),
('JSS1A', (select id from subjects where name = 'BT')),
('JSS1A', (select id from subjects where name = 'PHE')),
('JSS1A', (select id from subjects where name = 'Agriculture')),
('JSS1A', (select id from subjects where name = 'IRS')),
('JSS1A', (select id from subjects where name = 'Yoruba')),
('JSS1A', (select id from subjects where name = 'Social & Cit Ed')),
('JSS1A', (select id from subjects where name = 'French')),
('JSS1B', (select id from subjects where name = 'English')),
('JSS1B', (select id from subjects where name = 'Mathematics')),
('JSS1B', (select id from subjects where name = 'Basic Science')),
('JSS1B', (select id from subjects where name = 'CCA')),
('JSS1B', (select id from subjects where name = 'CRS')),
('JSS1B', (select id from subjects where name = 'History')),
('JSS1B', (select id from subjects where name = 'Horticulture')),
('JSS1B', (select id from subjects where name = 'Business Studies')),
('JSS1B', (select id from subjects where name = 'DT')),
('JSS1B', (select id from subjects where name = 'BT')),
('JSS1B', (select id from subjects where name = 'PHE')),
('JSS1B', (select id from subjects where name = 'Agriculture')),
('JSS1B', (select id from subjects where name = 'IRS')),
('JSS1B', (select id from subjects where name = 'Yoruba')),
('JSS1B', (select id from subjects where name = 'Social & Cit Ed')),
('JSS1B', (select id from subjects where name = 'French')),
('JSS2A', (select id from subjects where name = 'English')),
('JSS2A', (select id from subjects where name = 'Mathematics')),
('JSS2A', (select id from subjects where name = 'Basic Science')),
('JSS2A', (select id from subjects where name = 'CCA')),
('JSS2A', (select id from subjects where name = 'CRS')),
('JSS2A', (select id from subjects where name = 'History')),
('JSS2A', (select id from subjects where name = 'Horticulture')),
('JSS2A', (select id from subjects where name = 'Business Studies')),
('JSS2A', (select id from subjects where name = 'DT')),
('JSS2A', (select id from subjects where name = 'BT')),
('JSS2A', (select id from subjects where name = 'PHE')),
('JSS2A', (select id from subjects where name = 'Agriculture')),
('JSS2A', (select id from subjects where name = 'IRS')),
('JSS2A', (select id from subjects where name = 'Yoruba')),
('JSS2A', (select id from subjects where name = 'Social & Cit Ed')),
('JSS2A', (select id from subjects where name = 'French')),
('JSS2B', (select id from subjects where name = 'English')),
('JSS2B', (select id from subjects where name = 'Mathematics')),
('JSS2B', (select id from subjects where name = 'Basic Science')),
('JSS2B', (select id from subjects where name = 'CCA')),
('JSS2B', (select id from subjects where name = 'CRS')),
('JSS2B', (select id from subjects where name = 'History')),
('JSS2B', (select id from subjects where name = 'Horticulture')),
('JSS2B', (select id from subjects where name = 'Business Studies')),
('JSS2B', (select id from subjects where name = 'DT')),
('JSS2B', (select id from subjects where name = 'BT')),
('JSS2B', (select id from subjects where name = 'PHE')),
('JSS2B', (select id from subjects where name = 'Agriculture')),
('JSS2B', (select id from subjects where name = 'IRS')),
('JSS2B', (select id from subjects where name = 'Yoruba')),
('JSS2B', (select id from subjects where name = 'Social & Cit Ed')),
('JSS2B', (select id from subjects where name = 'French')),
('JSS3A', (select id from subjects where name = 'English')),
('JSS3A', (select id from subjects where name = 'Mathematics')),
('JSS3A', (select id from subjects where name = 'Basic Science')),
('JSS3A', (select id from subjects where name = 'CCA')),
('JSS3A', (select id from subjects where name = 'CRS')),
('JSS3A', (select id from subjects where name = 'History')),
('JSS3A', (select id from subjects where name = 'Horticulture')),
('JSS3A', (select id from subjects where name = 'Business Studies')),
('JSS3A', (select id from subjects where name = 'BT')),
('JSS3A', (select id from subjects where name = 'Computer')),
('JSS3A', (select id from subjects where name = 'NVE')),
('JSS3A', (select id from subjects where name = 'PHE')),
('JSS3A', (select id from subjects where name = 'Agriculture')),
('JSS3A', (select id from subjects where name = 'IRS')),
('JSS3A', (select id from subjects where name = 'Yoruba')),
('JSS3A', (select id from subjects where name = 'French')),
('JSS3B', (select id from subjects where name = 'English')),
('JSS3B', (select id from subjects where name = 'Mathematics')),
('JSS3B', (select id from subjects where name = 'Basic Science')),
('JSS3B', (select id from subjects where name = 'CCA')),
('JSS3B', (select id from subjects where name = 'CRS')),
('JSS3B', (select id from subjects where name = 'History')),
('JSS3B', (select id from subjects where name = 'Horticulture')),
('JSS3B', (select id from subjects where name = 'Business Studies')),
('JSS3B', (select id from subjects where name = 'BT')),
('JSS3B', (select id from subjects where name = 'Computer')),
('JSS3B', (select id from subjects where name = 'NVE')),
('JSS3B', (select id from subjects where name = 'PHE')),
('JSS3B', (select id from subjects where name = 'Agriculture')),
('JSS3B', (select id from subjects where name = 'IRS')),
('JSS3B', (select id from subjects where name = 'Yoruba')),
('JSS3B', (select id from subjects where name = 'French')),
('SS1 Science', (select id from subjects where name = 'English')),
('SS1 Science', (select id from subjects where name = 'Mathematics')),
('SS1 Science', (select id from subjects where name = 'Physics')),
('SS1 Science', (select id from subjects where name = 'Chemistry')),
('SS1 Science', (select id from subjects where name = 'Biology')),
('SS1 Science', (select id from subjects where name = 'Further Math')),
('SS1 Science', (select id from subjects where name = 'Data Processing')),
('SS1 Science', (select id from subjects where name = 'Commerce')),
('SS1 Science', (select id from subjects where name = 'Marketing')),
('SS1 Science', (select id from subjects where name = 'Agriculture')),
('SS1 Science', (select id from subjects where name = 'Livestock')),
('SS1 Science', (select id from subjects where name = 'Economics')),
('SS1 Science', (select id from subjects where name = 'History')),
('SS1 Science', (select id from subjects where name = 'Cit & Heritage')),
('SS1 Actuarial', (select id from subjects where name = 'English')),
('SS1 Actuarial', (select id from subjects where name = 'Mathematics')),
('SS1 Actuarial', (select id from subjects where name = 'Biology')),
('SS1 Actuarial', (select id from subjects where name = 'Data Processing')),
('SS1 Actuarial', (select id from subjects where name = 'Commerce')),
('SS1 Actuarial', (select id from subjects where name = 'Marketing')),
('SS1 Actuarial', (select id from subjects where name = 'Agriculture')),
('SS1 Actuarial', (select id from subjects where name = 'Livestock')),
('SS1 Actuarial', (select id from subjects where name = 'Economics')),
('SS1 Actuarial', (select id from subjects where name = 'History')),
('SS1 Actuarial', (select id from subjects where name = 'Cit & Heritage')),
('SS1 Actuarial', (select id from subjects where name = 'Government')),
('SS1 Actuarial', (select id from subjects where name = 'Yoruba')),
('SS1 Actuarial', (select id from subjects where name = 'CRS')),
('SS1 Actuarial', (select id from subjects where name = 'IRS')),
('SS1 Actuarial', (select id from subjects where name = 'Accounting')),
('SS1 Actuarial', (select id from subjects where name = 'Literature')),
('SS2 Science', (select id from subjects where name = 'English')),
('SS2 Science', (select id from subjects where name = 'Mathematics')),
('SS2 Science', (select id from subjects where name = 'Physics')),
('SS2 Science', (select id from subjects where name = 'Chemistry')),
('SS2 Science', (select id from subjects where name = 'Biology')),
('SS2 Science', (select id from subjects where name = 'Further Math')),
('SS2 Science', (select id from subjects where name = 'Data Processing')),
('SS2 Science', (select id from subjects where name = 'Commerce')),
('SS2 Science', (select id from subjects where name = 'Marketing')),
('SS2 Science', (select id from subjects where name = 'Agriculture')),
('SS2 Science', (select id from subjects where name = 'Livestock')),
('SS2 Science', (select id from subjects where name = 'Economics')),
('SS2 Science', (select id from subjects where name = 'History')),
('SS2 Science', (select id from subjects where name = 'Cit & Heritage')),
('SS2 Actuarial', (select id from subjects where name = 'English')),
('SS2 Actuarial', (select id from subjects where name = 'Mathematics')),
('SS2 Actuarial', (select id from subjects where name = 'Biology')),
('SS2 Actuarial', (select id from subjects where name = 'Data Processing')),
('SS2 Actuarial', (select id from subjects where name = 'Commerce')),
('SS2 Actuarial', (select id from subjects where name = 'Marketing')),
('SS2 Actuarial', (select id from subjects where name = 'Agriculture')),
('SS2 Actuarial', (select id from subjects where name = 'Livestock')),
('SS2 Actuarial', (select id from subjects where name = 'Economics')),
('SS2 Actuarial', (select id from subjects where name = 'History')),
('SS2 Actuarial', (select id from subjects where name = 'Cit & Heritage')),
('SS2 Actuarial', (select id from subjects where name = 'Government')),
('SS2 Actuarial', (select id from subjects where name = 'Yoruba')),
('SS2 Actuarial', (select id from subjects where name = 'CRS')),
('SS2 Actuarial', (select id from subjects where name = 'IRS')),
('SS2 Actuarial', (select id from subjects where name = 'Accounting')),
('SS2 Actuarial', (select id from subjects where name = 'Literature')),
('SS3 Science', (select id from subjects where name = 'English')),
('SS3 Science', (select id from subjects where name = 'Mathematics')),
('SS3 Science', (select id from subjects where name = 'Physics')),
('SS3 Science', (select id from subjects where name = 'Chemistry')),
('SS3 Science', (select id from subjects where name = 'Biology')),
('SS3 Science', (select id from subjects where name = 'Further Math')),
('SS3 Science', (select id from subjects where name = 'Data Processing')),
('SS3 Science', (select id from subjects where name = 'Commerce')),
('SS3 Science', (select id from subjects where name = 'Marketing')),
('SS3 Science', (select id from subjects where name = 'Agriculture')),
('SS3 Science', (select id from subjects where name = 'Livestock')),
('SS3 Science', (select id from subjects where name = 'Economics')),
('SS3 Science', (select id from subjects where name = 'History')),
('SS3 Science', (select id from subjects where name = 'Cit & Heritage')),
('SS3 Actuarial', (select id from subjects where name = 'English')),
('SS3 Actuarial', (select id from subjects where name = 'Mathematics')),
('SS3 Actuarial', (select id from subjects where name = 'Biology')),
('SS3 Actuarial', (select id from subjects where name = 'Data Processing')),
('SS3 Actuarial', (select id from subjects where name = 'Commerce')),
('SS3 Actuarial', (select id from subjects where name = 'Marketing')),
('SS3 Actuarial', (select id from subjects where name = 'Agriculture')),
('SS3 Actuarial', (select id from subjects where name = 'Livestock')),
('SS3 Actuarial', (select id from subjects where name = 'Economics')),
('SS3 Actuarial', (select id from subjects where name = 'History')),
('SS3 Actuarial', (select id from subjects where name = 'Cit & Heritage')),
('SS3 Actuarial', (select id from subjects where name = 'Government')),
('SS3 Actuarial', (select id from subjects where name = 'Yoruba')),
('SS3 Actuarial', (select id from subjects where name = 'CRS')),
('SS3 Actuarial', (select id from subjects where name = 'IRS')),
('SS3 Actuarial', (select id from subjects where name = 'Accounting')),
('SS3 Actuarial', (select id from subjects where name = 'Literature'))
on conflict do nothing;

insert into students (id, full_name, class_id) values
('TCH-2025-001', 'Abraham Comfort Princess', 'JSS1A'),
('TCH-2025-002', 'Abraham Nanmwa', 'JSS1A'),
('TCH-2025-003', 'Adebanjo Anjola', 'JSS1A'),
('TCH-2025-004', 'Adegboye Adam', 'JSS1A'),
('TCH-2025-005', 'Ademola Daniel', 'JSS1A'),
('TCH-2025-006', 'Adeoye Ikimot', 'JSS1A'),
('TCH-2025-007', 'Adeyemi Olamide', 'JSS1A'),
('TCH-2025-008', 'Adiukwu Chimuanya', 'JSS1A'),
('TCH-2025-009', 'Ayegba Anthony', 'JSS1A'),
('TCH-2025-010', 'Chris Ukpah Rejoice', 'JSS1A'),
('TCH-2025-011', 'Ehigie Jeffrey', 'JSS1A'),
('TCH-2025-012', 'Enabulele Newton', 'JSS1A'),
('TCH-2025-013', 'Hamzat Alaba', 'JSS1A'),
('TCH-2025-014', 'Idowu Taiwo', 'JSS1A'),
('TCH-2025-015', 'Jackson Grace', 'JSS1A'),
('TCH-2025-016', 'Jimoh Sodiq', 'JSS1A'),
('TCH-2025-017', 'Mohammed Abdul-salam', 'JSS1A'),
('TCH-2025-018', 'Muritala Farhan', 'JSS1A'),
('TCH-2025-019', 'Obaoye Adeola Ruth', 'JSS1A'),
('TCH-2025-020', 'Oduwaye Abdul-salam', 'JSS1A'),
('TCH-2025-021', 'Ogunlana Aishat', 'JSS1A'),
('TCH-2025-022', 'Okwuabudike Michael', 'JSS1A'),
('TCH-2025-023', 'Olukoga Akorede', 'JSS1A'),
('TCH-2025-024', 'Oni Grace Oluwadarasimi', 'JSS1A'),
('TCH-2025-025', 'Otuole Innocent', 'JSS1A'),
('TCH-2025-026', 'Peter John', 'JSS1A'),
('TCH-2025-027', 'Rafiu Aishat', 'JSS1A'),
('TCH-2025-028', 'Soyode Emmanuel', 'JSS1A'),
('TCH-2025-029', 'Yusuf Al-meen', 'JSS1A'),
('TCH-2025-030', 'Adeniyi Nifemi', 'JSS1B'),
('TCH-2025-031', 'Adeniyi Basit', 'JSS1B'),
('TCH-2025-032', 'Adeyemi Modesire', 'JSS1B'),
('TCH-2025-033', 'Agbo Wonderful', 'JSS1B'),
('TCH-2025-034', 'Akeju Emmanuel', 'JSS1B'),
('TCH-2025-035', 'Akindutire Michael', 'JSS1B'),
('TCH-2025-036', 'Asuluka Obioma', 'JSS1B'),
('TCH-2025-037', 'Babarinde Testimony', 'JSS1B'),
('TCH-2025-038', 'Dada Ayodeji', 'JSS1B'),
('TCH-2025-039', 'Dickson Samson', 'JSS1B'),
('TCH-2025-040', 'Idowu Kehinde', 'JSS1B'),
('TCH-2025-041', 'Ikujuni Samuel', 'JSS1B'),
('TCH-2025-042', 'Irinyemi Halleluyah', 'JSS1B'),
('TCH-2025-043', 'Ishola Suliat', 'JSS1B'),
('TCH-2025-044', 'Jewoola Olamide', 'JSS1B'),
('TCH-2025-045', 'Jonathan Frednard', 'JSS1B'),
('TCH-2025-046', 'Makinde Tofunmi', 'JSS1B'),
('TCH-2025-047', 'Odulate Boluwatife', 'JSS1B'),
('TCH-2025-048', 'Okezueze Ifechukwu', 'JSS1B'),
('TCH-2025-049', 'Oni Fikayo', 'JSS1B'),
('TCH-2025-050', 'Onibodo Quadri', 'JSS1B'),
('TCH-2025-051', 'Owoade Praise', 'JSS1B'),
('TCH-2025-052', 'Oyeniran Michelle', 'JSS1B'),
('TCH-2025-053', 'Safiriyu Simisola', 'JSS1B'),
('TCH-2025-054', 'Sandy Enoch', 'JSS1B'),
('TCH-2025-055', 'Shokoya Imole', 'JSS1B'),
('TCH-2025-056', 'Tijani Anjolaoluwa', 'JSS1B'),
('TCH-2025-057', 'Ubi Richard Victoria', 'JSS1B'),
('TCH-2025-058', 'Yusuff Salamat Semilore', 'JSS1B'),
('TCH-2025-059', 'Abey Phoebe', 'JSS2A'),
('TCH-2025-060', 'Adeniyi Mubarak', 'JSS2A'),
('TCH-2025-061', 'Agbabiaka Ella', 'JSS2A'),
('TCH-2025-062', 'Alaka Faridat', 'JSS2A'),
('TCH-2025-063', 'Aramide Hikimot', 'JSS2A'),
('TCH-2025-064', 'Aremu Praise', 'JSS2A'),
('TCH-2025-065', 'Ayoade Flourish', 'JSS2A'),
('TCH-2025-066', 'Bakare Gabriel', 'JSS2A'),
('TCH-2025-067', 'Bamiro David', 'JSS2A'),
('TCH-2025-068', 'Biobaku Azraa', 'JSS2A'),
('TCH-2025-069', 'Boladale Esther', 'JSS2A'),
('TCH-2025-070', 'Edeniyi Ukharia', 'JSS2A'),
('TCH-2025-071', 'Falope Kikiope', 'JSS2A'),
('TCH-2025-072', 'Ida Wisdom', 'JSS2A'),
('TCH-2025-073', 'Mudashiru Abidat', 'JSS2A'),
('TCH-2025-074', 'Muh''awwal Alitorf', 'JSS2A'),
('TCH-2025-075', 'Musa Isaac', 'JSS2A'),
('TCH-2025-076', 'Neri Testimony', 'JSS2A'),
('TCH-2025-077', 'Obaoye Dorcas', 'JSS2A'),
('TCH-2025-078', 'Ogoyemi Josephine', 'JSS2A'),
('TCH-2025-079', 'Olowu Jamal', 'JSS2A'),
('TCH-2025-080', 'Olubiyi Godwin', 'JSS2A'),
('TCH-2025-081', 'Opeyemi Rosheedat', 'JSS2A'),
('TCH-2025-082', 'Oriabor Joy', 'JSS2A'),
('TCH-2025-083', 'Orukpe Daniel', 'JSS2A'),
('TCH-2025-084', 'Oyeboade Erioluwa', 'JSS2A'),
('TCH-2025-085', 'Oyediji Israel', 'JSS2A'),
('TCH-2025-086', 'Oyetunji Adejoke', 'JSS2A'),
('TCH-2025-087', 'Oyewole Daniel', 'JSS2A'),
('TCH-2025-088', 'Rafiu Rofiat', 'JSS2A'),
('TCH-2025-089', 'Raji Joshua', 'JSS2A'),
('TCH-2025-090', 'Tijani Olamiposi', 'JSS2A'),
('TCH-2025-091', 'Abolanle Nancy', 'JSS2B'),
('TCH-2025-092', 'Adeboyo Taiwo', 'JSS2B'),
('TCH-2025-093', 'Adeniran Isaac', 'JSS2B'),
('TCH-2025-094', 'Adesuyi Ademola', 'JSS2B'),
('TCH-2025-095', 'Akinade Darasimi', 'JSS2B'),
('TCH-2025-096', 'Akinola Abdulhamid', 'JSS2B'),
('TCH-2025-097', 'Alexander Chinaza', 'JSS2B'),
('TCH-2025-098', 'Balogun Muminat', 'JSS2B'),
('TCH-2025-099', 'Fagbola Oladerin Emmanualla', 'JSS2B'),
('TCH-2025-100', 'Ganiu Aliyat', 'JSS2B'),
('TCH-2025-101', 'Idris Faridat', 'JSS2B'),
('TCH-2025-102', 'Ikechukwu Miracle', 'JSS2B'),
('TCH-2025-103', 'Kamilu Saheed', 'JSS2B'),
('TCH-2025-104', 'Muritala Rokibat', 'JSS2B'),
('TCH-2025-105', 'Ochege Rhoda', 'JSS2B'),
('TCH-2025-106', 'Ojochegbe Linda', 'JSS2B'),
('TCH-2025-107', 'Olaniyi Mary', 'JSS2B'),
('TCH-2025-108', 'Olatunbosun Daniel', 'JSS2B'),
('TCH-2025-109', 'Ologunre Marvellous', 'JSS2B'),
('TCH-2025-110', 'Onifade Ayomide', 'JSS2B'),
('TCH-2025-111', 'Oseni Idayat', 'JSS2B'),
('TCH-2025-112', 'Sakiru John', 'JSS2B'),
('TCH-2025-113', 'Shofowora Nifemi', 'JSS2B'),
('TCH-2025-114', 'Suli Fridaus', 'JSS2B'),
('TCH-2025-115', 'Yakubu Moses', 'JSS2B'),
('TCH-2025-116', 'Abdul Rasheed Rodiat', 'JSS3A'),
('TCH-2025-117', 'Adebayo Dorcas', 'JSS3A'),
('TCH-2025-118', 'Adebayo Favour', 'JSS3A'),
('TCH-2025-119', 'Adeniyi Darasimi', 'JSS3A'),
('TCH-2025-120', 'Afolayan Joshua', 'JSS3A'),
('TCH-2025-121', 'Akanji Favour', 'JSS3A'),
('TCH-2025-122', 'Akinbiyi Glory', 'JSS3A'),
('TCH-2025-123', 'Amusat Khalilulahi O', 'JSS3A'),
('TCH-2025-124', 'Faruk Aransiola', 'JSS3A'),
('TCH-2025-125', 'Balogun Jomiloju', 'JSS3A'),
('TCH-2025-126', 'Emmanuel Ayowole', 'JSS3A'),
('TCH-2025-127', 'Emmanuel Maxwell', 'JSS3A'),
('TCH-2025-128', 'Emmanuel Priscilla', 'JSS3A'),
('TCH-2025-129', 'Fatuki Oluwanifemi', 'JSS3A'),
('TCH-2025-130', 'Folorunsho Precious', 'JSS3A'),
('TCH-2025-131', 'Garba Albarka', 'JSS3A'),
('TCH-2025-132', 'Ibhadore Godswill', 'JSS3A'),
('TCH-2025-133', 'Irinyemi Jomiloju Praise', 'JSS3A'),
('TCH-2025-134', 'Kolade Idera', 'JSS3A'),
('TCH-2025-135', 'Nanmwa Victor', 'JSS3A'),
('TCH-2025-136', 'Nathaniel David', 'JSS3A'),
('TCH-2025-137', 'Nelson Sonia C.C', 'JSS3A'),
('TCH-2025-138', 'Nyakos Nurudeen', 'JSS3A'),
('TCH-2025-139', 'Ogunlana Abdullahi', 'JSS3A'),
('TCH-2025-140', 'Okwuabudike Victoria', 'JSS3A'),
('TCH-2025-141', 'Olatunji Al-meen', 'JSS3A'),
('TCH-2025-142', 'Olowu Fausiyat', 'JSS3A'),
('TCH-2025-143', 'Oluborode True Vine', 'JSS3A'),
('TCH-2025-144', 'Oseni Abdulsamod', 'JSS3A'),
('TCH-2025-145', 'Owoyele Ramadan', 'JSS3A'),
('TCH-2025-146', 'Oyewole Israel', 'JSS3A'),
('TCH-2025-147', 'Salawudeen Fawas', 'JSS3A'),
('TCH-2025-148', 'Sunny Blessing', 'JSS3A'),
('TCH-2025-149', 'Waheed Aduragbemi', 'JSS3A'),
('TCH-2025-150', 'Wisdom Donald', 'JSS3A'),
('TCH-2025-151', 'Yusuf Taiwo', 'JSS3A'),
('TCH-2025-152', 'Yusuff Abdul Sattar', 'JSS3A'),
('TCH-2025-153', 'Abdul Razak Somod', 'JSS3B'),
('TCH-2025-154', 'Adebisi Aishat', 'JSS3B'),
('TCH-2025-155', 'Adebisi Ayomide', 'JSS3B'),
('TCH-2025-156', 'Adebisi Yusuf', 'JSS3B'),
('TCH-2025-157', 'Adeniyi Korede', 'JSS3B'),
('TCH-2025-158', 'Adewunmi Oluwademilade', 'JSS3B'),
('TCH-2025-159', 'Agbo Favour', 'JSS3B'),
('TCH-2025-160', 'Akinfe Christianah', 'JSS3B'),
('TCH-2025-161', 'Ambrose Emmanuella', 'JSS3B'),
('TCH-2025-162', 'Ariyo Moses', 'JSS3B'),
('TCH-2025-163', 'Ayoade Doris', 'JSS3B'),
('TCH-2025-164', 'Balogun Tobiloba', 'JSS3B'),
('TCH-2025-165', 'Enabulele Israel', 'JSS3B'),
('TCH-2025-166', 'Faluyi Israel', 'JSS3B'),
('TCH-2025-167', 'Folorunsho Alexander', 'JSS3B'),
('TCH-2025-168', 'Gabriel Peace', 'JSS3B'),
('TCH-2025-169', 'Lawal Esther', 'JSS3B'),
('TCH-2025-170', 'Medua Angel', 'JSS3B'),
('TCH-2025-171', 'Nyakos Naimat', 'JSS3B'),
('TCH-2025-172', 'Olajesu Kayode', 'JSS3B'),
('TCH-2025-173', 'Olasunkanmi Ayobami', 'JSS3B'),
('TCH-2025-174', 'Olukotun Feranmi', 'JSS3B'),
('TCH-2025-175', 'Onafowokan Ridwan', 'JSS3B'),
('TCH-2025-176', 'Opatimeyin David', 'JSS3B'),
('TCH-2025-177', 'Oyeniyi David', 'JSS3B'),
('TCH-2025-178', 'Popoola Aduragbemi', 'JSS3B'),
('TCH-2025-179', 'Rotimi Eniola', 'JSS3B'),
('TCH-2025-180', 'Samson Loveth', 'JSS3B'),
('TCH-2025-181', 'Samuel Zainab', 'JSS3B'),
('TCH-2025-182', 'Soyode Emmanuella', 'JSS3B'),
('TCH-2025-183', 'Uduakhomo Peace', 'JSS3B'),
('TCH-2025-184', 'Abdullateef Abdulsalam', 'SS1 Science'),
('TCH-2025-185', 'Abimbola Israel', 'SS1 Science'),
('TCH-2025-186', 'Adebayo Ayomide', 'SS1 Science'),
('TCH-2025-187', 'Adesalu Kamal', 'SS1 Science'),
('TCH-2025-188', 'Adeshina Fawaz', 'SS1 Science'),
('TCH-2025-189', 'Ajayi Aminat', 'SS1 Science'),
('TCH-2025-190', 'Ajewole Darasimi', 'SS1 Science'),
('TCH-2025-191', 'Ajibola Rodiat', 'SS1 Science'),
('TCH-2025-192', 'Akinyogha Taiwo', 'SS1 Science'),
('TCH-2025-193', 'Akoshile Hameedah', 'SS1 Science'),
('TCH-2025-194', 'Akpoveta Daniel', 'SS1 Science'),
('TCH-2025-195', 'Alexander Chukwu', 'SS1 Science'),
('TCH-2025-196', 'Amos Savior', 'SS1 Science'),
('TCH-2025-197', 'Ashaye Damola', 'SS1 Science'),
('TCH-2025-198', 'Ayangbola Dammilola', 'SS1 Science'),
('TCH-2025-199', 'Bakare Amirat', 'SS1 Science'),
('TCH-2025-200', 'Bakare Nifemi', 'SS1 Science'),
('TCH-2025-201', 'Balogun Momeen', 'SS1 Science'),
('TCH-2025-202', 'Bamidele Goodluck', 'SS1 Science'),
('TCH-2025-203', 'Chukwuemeka Favour', 'SS1 Science'),
('TCH-2025-204', 'Durosimi Abdullateef', 'SS1 Science'),
('TCH-2025-205', 'Emmanuel Godiva', 'SS1 Science'),
('TCH-2025-206', 'Fatai Muinat', 'SS1 Science'),
('TCH-2025-207', 'Folorunsho Elijah', 'SS1 Science'),
('TCH-2025-208', 'Hassanat', 'SS1 Science'),
('TCH-2025-209', 'Hilary Favour', 'SS1 Science'),
('TCH-2025-210', 'Jimoh Yewande', 'SS1 Science'),
('TCH-2025-211', 'Julius-Caleb Okenwan', 'SS1 Science'),
('TCH-2025-212', 'Lawal Promise', 'SS1 Science'),
('TCH-2025-213', 'Momoh Divine', 'SS1 Science'),
('TCH-2025-214', 'Musa Nimotallahi', 'SS1 Science'),
('TCH-2025-215', 'Ogbueje Nannette', 'SS1 Science'),
('TCH-2025-216', 'Ogbonna Joshua', 'SS1 Science'),
('TCH-2025-217', 'Ojo Precious', 'SS1 Science'),
('TCH-2025-218', 'Okebiyi Blessing', 'SS1 Science'),
('TCH-2025-219', 'Okebugwu Michael', 'SS1 Science'),
('TCH-2025-220', 'Oladipo Oluwabukola', 'SS1 Science'),
('TCH-2025-221', 'Olalere Halim', 'SS1 Science'),
('TCH-2025-222', 'Olaniyan Emmanuel', 'SS1 Science'),
('TCH-2025-223', 'Olubiyi Olamide', 'SS1 Science'),
('TCH-2025-224', 'Oluwatoyin Eniola', 'SS1 Science'),
('TCH-2025-225', 'Oni Ezekiel', 'SS1 Science'),
('TCH-2025-226', 'Onwuegbule Wisdom', 'SS1 Science'),
('TCH-2025-227', 'Opaje Teniola', 'SS1 Science'),
('TCH-2025-228', 'Opeyemi Michael', 'SS1 Science'),
('TCH-2025-229', 'Opeyemi Sultan', 'SS1 Science'),
('TCH-2025-230', 'Oyesanya Israel', 'SS1 Science'),
('TCH-2025-231', 'Samuel Benjamin', 'SS1 Science'),
('TCH-2025-232', 'Sanusi Farahat', 'SS1 Science'),
('TCH-2025-233', 'Sunday Isaac', 'SS1 Science'),
('TCH-2025-234', 'Abdulmateen saheed', 'SS1 Actuarial'),
('TCH-2025-235', 'Arekwen clement', 'SS1 Actuarial'),
('TCH-2025-236', 'Ekum honesty', 'SS1 Actuarial'),
('TCH-2025-237', 'Kehinde anjolaoluwa', 'SS1 Actuarial'),
('TCH-2025-238', 'Khalid lateef', 'SS1 Actuarial'),
('TCH-2025-239', 'Oche ojochegbe michael', 'SS1 Actuarial'),
('TCH-2025-240', 'Olajire anuoluwapo', 'SS1 Actuarial'),
('TCH-2025-241', 'Oni peter', 'SS1 Actuarial'),
('TCH-2025-242', 'Rafiu kehinde', 'SS1 Actuarial'),
('TCH-2025-243', 'Rafiu taiwo', 'SS1 Actuarial'),
('TCH-2025-244', 'Kolawole rereoluwa', 'SS1 Actuarial'),
('TCH-2025-245', 'James goodluck', 'SS1 Actuarial'),
('TCH-2025-246', 'Azeez malik', 'SS1 Actuarial'),
('TCH-2025-247', 'Aiwe Destiny', 'SS1 Actuarial'),
('TCH-2025-248', 'Friday Destiny', 'SS1 Actuarial'),
('TCH-2025-249', 'Akeju David', 'SS1 Actuarial'),
('TCH-2025-250', 'Mohammed fayade', 'SS1 Actuarial'),
('TCH-2025-251', 'Adeyemo ikimat', 'SS1 Actuarial'),
('TCH-2025-252', 'Ajayi fiyinfoluwa', 'SS1 Actuarial'),
('TCH-2025-253', 'Bello opeyemi', 'SS1 Actuarial'),
('TCH-2025-254', 'Falope oluwajomiloju', 'SS1 Actuarial'),
('TCH-2025-255', 'Fowowe Abigail', 'SS1 Actuarial'),
('TCH-2025-256', 'Idowu Amidat', 'SS1 Actuarial'),
('TCH-2025-257', 'Ikujuni Oluwasikemi', 'SS1 Actuarial'),
('TCH-2025-258', 'Livinus chioma', 'SS1 Actuarial'),
('TCH-2025-259', 'Olukoja omowunmi', 'SS1 Actuarial'),
('TCH-2025-260', 'Onojah Victoria', 'SS1 Actuarial'),
('TCH-2025-261', 'Tijani Aishat', 'SS1 Actuarial'),
('TCH-2025-262', 'Tujiki anuoluwapo', 'SS1 Actuarial'),
('TCH-2025-263', 'Idris mariam', 'SS1 Actuarial'),
('TCH-2025-264', 'Nosiru halimat', 'SS1 Actuarial'),
('TCH-2025-265', 'Adeyemi mariam', 'SS1 Actuarial'),
('TCH-2025-266', 'Akinyugha kehinde', 'SS1 Actuarial'),
('TCH-2025-267', 'Musa emmanuella', 'SS1 Actuarial'),
('TCH-2025-268', 'Awodiya Amazing-Grace', 'SS1 Actuarial'),
('TCH-2025-269', 'Ofonime Success', 'SS1 Actuarial'),
('TCH-2025-270', 'Abdullahi Malik', 'SS2 Science'),
('TCH-2025-271', 'Adeoye Rokeeb', 'SS2 Science'),
('TCH-2025-272', 'Adeyemi Adesewa', 'SS2 Science'),
('TCH-2025-273', 'Adeyemi Emmanuel', 'SS2 Science'),
('TCH-2025-274', 'Agbo Queen', 'SS2 Science'),
('TCH-2025-275', 'Akindutire Iretiola', 'SS2 Science'),
('TCH-2025-276', 'Alejo Samuel', 'SS2 Science'),
('TCH-2025-277', 'Babalola Rodiat', 'SS2 Science'),
('TCH-2025-278', 'Bakare Aliyat', 'SS2 Science'),
('TCH-2025-279', 'Eke Erica', 'SS2 Science'),
('TCH-2025-280', 'Emmanuel Annabel', 'SS2 Science'),
('TCH-2025-281', 'Enabulele Itohan', 'SS2 Science'),
('TCH-2025-282', 'Friday Godspower', 'SS2 Science'),
('TCH-2025-283', 'Igbenedion Folabomi', 'SS2 Science'),
('TCH-2025-284', 'Itama Daniel', 'SS2 Science'),
('TCH-2025-285', 'Jimoh Ganiyat', 'SS2 Science'),
('TCH-2025-286', 'Mohammed Awwal', 'SS2 Science'),
('TCH-2025-287', 'Mudashiru Usman', 'SS2 Science'),
('TCH-2025-288', 'Nelson Victor', 'SS2 Science'),
('TCH-2025-289', 'Oduola Olamide', 'SS2 Science'),
('TCH-2025-290', 'Okwabudike Mercy', 'SS2 Science'),
('TCH-2025-291', 'Olagbo Susan', 'SS2 Science'),
('TCH-2025-292', 'Olaniyi David', 'SS2 Science'),
('TCH-2025-293', 'Olushesi Basit', 'SS2 Science'),
('TCH-2025-294', 'Omotosho Faith', 'SS2 Science'),
('TCH-2025-295', 'Oyebanji Victoria', 'SS2 Science'),
('TCH-2025-296', 'Oyedeji Emmanuella', 'SS2 Science'),
('TCH-2025-297', 'Quadri Oluwadarasimi', 'SS2 Science'),
('TCH-2025-298', 'Sandy Karenapuch', 'SS2 Science'),
('TCH-2025-299', 'Sanyaolu Kehinde', 'SS2 Science'),
('TCH-2025-300', 'Sanyaolu Taiwo', 'SS2 Science'),
('TCH-2025-301', 'Sulaimon Alimoh', 'SS2 Science'),
('TCH-2025-302', 'Sunday Mary', 'SS2 Science'),
('TCH-2025-303', 'Abdulrazak Abdulrahman', 'SS2 Actuarial'),
('TCH-2025-304', 'Abdusalam Timileyin', 'SS2 Actuarial'),
('TCH-2025-305', 'Abisoye Gold', 'SS2 Actuarial'),
('TCH-2025-306', 'Adebayo Isaiah', 'SS2 Actuarial'),
('TCH-2025-307', 'Adeniyi Gbolahan', 'SS2 Actuarial'),
('TCH-2025-308', 'Adenola Darasimi', 'SS2 Actuarial'),
('TCH-2025-309', 'Agboola Daniel', 'SS2 Actuarial'),
('TCH-2025-310', 'Azeez Wazilat', 'SS2 Actuarial'),
('TCH-2025-311', 'Bakare Bolaji', 'SS2 Actuarial'),
('TCH-2025-312', 'Chukwu Samuel', 'SS2 Actuarial'),
('TCH-2025-313', 'Ebere Larry', 'SS2 Actuarial'),
('TCH-2025-314', 'Eduniyi Gideon', 'SS2 Actuarial'),
('TCH-2025-315', 'Ewenla Noah', 'SS2 Actuarial'),
('TCH-2025-316', 'Ibadore Miracle', 'SS2 Actuarial'),
('TCH-2025-317', 'Ipadeola Idris', 'SS2 Actuarial'),
('TCH-2025-318', 'Ipadeola Quadri', 'SS2 Actuarial'),
('TCH-2025-319', 'Jewoola Boluwatife', 'SS2 Actuarial'),
('TCH-2025-320', 'Lawal Gabriel', 'SS2 Actuarial'),
('TCH-2025-321', 'Mathew Glory', 'SS2 Actuarial'),
('TCH-2025-322', 'Njoh Ifeoma', 'SS2 Actuarial'),
('TCH-2025-323', 'Nwaeke Maryann', 'SS2 Actuarial'),
('TCH-2025-324', 'Ochege Sunday', 'SS2 Actuarial'),
('TCH-2025-325', 'Okarfor Ifeoma', 'SS2 Actuarial'),
('TCH-2025-326', 'Oladeji Ala-meen', 'SS2 Actuarial'),
('TCH-2025-327', 'Osiba Temiloluwa', 'SS2 Actuarial'),
('TCH-2025-328', 'Osunubi Gbolahan', 'SS2 Actuarial'),
('TCH-2025-329', 'Oyebode Precious', 'SS2 Actuarial'),
('TCH-2025-330', 'Peter Godwin', 'SS2 Actuarial'),
('TCH-2025-331', 'Shobowale Isaac', 'SS2 Actuarial'),
('TCH-2025-332', 'Shokoya Samuel', 'SS2 Actuarial'),
('TCH-2025-333', 'Sulaimon Aishat', 'SS2 Actuarial'),
('TCH-2025-334', 'Zulukadeen Rokeeb', 'SS2 Actuarial'),
('TCH-2025-335', 'Angel', 'SS3 Science'),
('TCH-2025-336', 'Bamise', 'SS3 Science'),
('TCH-2025-337', 'Bright', 'SS3 Science'),
('TCH-2025-338', 'Dorcas', 'SS3 Science'),
('TCH-2025-339', 'Enoch', 'SS3 Science'),
('TCH-2025-340', 'Famous', 'SS3 Science'),
('TCH-2025-341', 'Fauziyyah', 'SS3 Science'),
('TCH-2025-342', 'Fawaz', 'SS3 Science'),
('TCH-2025-343', 'Fiyin', 'SS3 Science'),
('TCH-2025-344', 'Habitat', 'SS3 Science'),
('TCH-2025-345', 'Kaosara', 'SS3 Science'),
('TCH-2025-346', 'Khadija', 'SS3 Science'),
('TCH-2025-347', 'Mercy', 'SS3 Science'),
('TCH-2025-348', 'Michael', 'SS3 Science'),
('TCH-2025-349', 'Moyin', 'SS3 Science'),
('TCH-2025-350', 'Prosper', 'SS3 Science'),
('TCH-2025-351', 'Rita', 'SS3 Science'),
('TCH-2025-352', 'Rokibat', 'SS3 Science'),
('TCH-2025-353', 'Samuel', 'SS3 Science'),
('TCH-2025-354', 'Taiwo', 'SS3 Science'),
('TCH-2025-355', 'Temi', 'SS3 Science'),
('TCH-2025-356', 'Zainab', 'SS3 Science'),
('TCH-2025-357', 'Abdul Majeed Quadri', 'SS3 Actuarial'),
('TCH-2025-358', 'Abdul Razak Kehinde', 'SS3 Actuarial'),
('TCH-2025-359', 'Abuh God''s Power', 'SS3 Actuarial'),
('TCH-2025-360', 'Adebayo David', 'SS3 Actuarial'),
('TCH-2025-361', 'Adeniran Moses', 'SS3 Actuarial'),
('TCH-2025-362', 'Adesanya Emmanuel', 'SS3 Actuarial'),
('TCH-2025-363', 'Adisa Fathia', 'SS3 Actuarial'),
('TCH-2025-364', 'Ajibola Roheemot', 'SS3 Actuarial'),
('TCH-2025-365', 'Amos Wisdom', 'SS3 Actuarial'),
('TCH-2025-366', 'Asiemor Divine', 'SS3 Actuarial'),
('TCH-2025-367', 'Enemali Ojotoeba', 'SS3 Actuarial'),
('TCH-2025-368', 'Falope Darasimi', 'SS3 Actuarial'),
('TCH-2025-369', 'Famakinwa Akorede', 'SS3 Actuarial'),
('TCH-2025-370', 'Folorunsho Petra', 'SS3 Actuarial'),
('TCH-2025-371', 'Muritala Rashidat', 'SS3 Actuarial'),
('TCH-2025-372', 'Olalere Aishat', 'SS3 Actuarial'),
('TCH-2025-373', 'Oyekan Emmanuel', 'SS3 Actuarial'),
('TCH-2025-374', 'Sowole Azeem', 'SS3 Actuarial'),
('TCH-2025-375', 'Tujiki David', 'SS3 Actuarial'),
('TCH-2025-376', 'Yakubu Happiness', 'SS3 Actuarial');
